 steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/tebengan-project/${_TEBENGAN_SERVICE_NAME}:${SHORT_SHA}', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/tebengan-project/${_TEBENGAN_SERVICE_NAME}:${SHORT_SHA}']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'SERVICE_NAME'
    - '--image'
    - 'gcr.io/tebengan-project/${_TEBENGAN_SERVICE_NAME}:${SHORT_SHA}'
    - '--region'
    - 'SERVICE_REGION'
  images:
  - 'gcr.io/tebengan-project/${_TEBENGAN_SERVICE_NAME}:${SHORT_SHA}'